name: Compile FBNeo for CHA

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Sync fork"]
    types:
      - completed

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ACTIONS_ALLOW_UNSECURE_NODE_VERSION: true

jobs:
  build-and-release:
    runs-on: ubuntu-24.04
    container: node:16
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
    steps:
      - name: Install needed tools
        run: |
          echo "NOW=$(date +%F)" >> "$GITHUB_ENV"
          dpkg --add-architecture armhf
          apt-get update; apt-get upgrade --assume-yes
          apt-get install --assume-yes binutils-multiarch build-essential ca-certificates gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf curl git zip libudev-dev:armhf libsdl2-dev:armhf libsdl2-image-dev:armhf
          apt-get autoremove; apt-get autoclean
          echo '*** TEST LINUX VERSION ***'
          cat /etc/os-release
          echo '*** TEST GLIBC VERSION ***'
          ldd --version
      - name: Compile FinalBurn Neo for CHA
        run: |
          git config --global --add safe.directory ${PWD}
          git clone "https://${GITHUB_REPOSITORY_OWNER}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
          CROSS_COMP=1 RELEASEBUILD=1 make sdl2
          mv ./fbneo ./FinalBurn\ Neo\ for\ CHA/
          mv ./metadata/hiscore.dat ./FinalBurn\ Neo\ for\ CHA/
          echo "${{ env.NOW }}" > ./FinalBurn\ Neo\ for\ CHA/fbneo_build_date.txt
          mv ./README.md ./FinalBurn\ Neo\ for\ CHA/_README_.TXT
          zip -9 -r ./FinalBurn\ Neo\ for\ CHA.zip ./FinalBurn\ Neo\ for\ CHA
          mkdir ./FinalBurn\ Neo\ for\ CHA\ -\ Help\ Videos
          mv *.mp4 ./FinalBurn\ Neo\ for\ CHA\ -\ Help\ Videos/
          zip -9 -r ./FinalBurn\ Neo\ for\ CHA\ -\ Help\ Videos.zip ./FinalBurn\ Neo\ for\ CHA\ -\ Help\ Videos
      - name: Compile fbneo_libretro.so
        run: |
          CROSS_COMP=1 make -j$(nproc) -C src/burner/libretro generate-files platform=unix_rpi2
          CROSS_COMP=1 make -j$(nproc) -C src/burner/libretro platform=unix_rpi2
          mv src/burner/libretro/fbneo_libretro.so ./fbneo_libretro.${{ env.NOW }}.so
          zip -9 fbneo_libretro.zip fbneo_libretro*.so
      - name: Release FinalBurn Neo for CHA
        uses: softprops/action-gh-release@master
        with:
          files: |
            ./FinalBurn\ Neo\ for\ CHA.zip
            ./FinalBurn\ Neo\ for\ CHA\ -\ Help\ Videos.zip
          tag_name: fbneo-${{ env.NOW }}
          generate_release_notes: true
          name: FinalBurn Neo for CHA (${{ env.NOW }})
      - name: Release FinalBurn Neo libretro core for CHA
        uses: softprops/action-gh-release@master
        with:
          files: ./fbneo_libretro.zip
          tag_name: libretro-fbneo-${{ env.NOW }}
          generate_release_notes: false
          name: FinalBurn Neo libretro core for CHA (${{ env.NOW }})
      - name: Release FinalBurn Neo libretro core for CHA
        uses: softprops/action-gh-release@master
        with:
          files: ./fbneo_libretro.zip
          tag_name: libretro-latest
          generate_release_notes: false
          name: FinalBurn Neo libretro core for CHA (${{ env.NOW }})
      - name: Release FinalBurn Neo for CHA
        uses: softprops/action-gh-release@master
        with:
          files: |
            ./FinalBurn\ Neo\ for\ CHA.zip
            ./FinalBurn\ Neo\ for\ CHA\ -\ Help\ Videos.zip
          tag_name: latest
          make_latest: true
          generate_release_notes: false
          name: FinalBurn Neo for CHA (${{ env.NOW }})
      - uses: sgpublic/delete-release-action@v1.2
        with:
          release-drop: true
          release-keep-count: 14
          release-drop-tag: false
          pre-release-drop: true
          pre-release-keep-count: -1
          pre-release-drop-tag: true
          draft-drop: true
          draft-drop-count: -1
