name: Compile FBNeo for CHA

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  workflow_run:
    workflows: ["Sync fork"]
    types:
      - completed

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-release:
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
    steps:
      - name: Install needed tools
        run: |
          echo "NOW=$(date +%F)" >> "$GITHUB_ENV"
          sudo dpkg --add-architecture armhf
          sudo echo -e "Types: deb\nURIs: mirror+file:/etc/apt/apt-mirrors.txt\nArchitectures: amd64\nSuites: noble noble-updates noble-backports noble-security\nComponents: main universe restricted multiverse\nSigned-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg\n\nTypes: deb\nURIs: http://ports.ubuntu.com/\nArchitectures: armhf\nSuites: noble noble-updates noble-backports noble-security\nComponents: main universe restricted multiverse\nSigned-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg" | sudo tee /etc/apt/sources.list.d/ubuntu.sources
          sudo apt-get update || true
          sudo apt-get install libglib2.0-dev-bin:armhf=2.80.0-6ubuntu3.2 libglib2.0-dev-bin-linux:armhf=2.80.0-6ubuntu3.2
          echo "*** /etc/apt/sources.list.d/ubuntu.sources"
          cat /etc/apt/sources.list.d/ubuntu.sources
          sudo apt-get install --assume-yes curl ca-certificates build-essential zip git libudev-dev:armhf libsdl2-dev:armhf libsdl2-image-dev:armhf
      - name: Compile FinalBurn Neo for CHA
        run: |
          git clone "https://${GITHUB_REPOSITORY_OWNER}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
          git config --global --add safe.directory "$PWD"
          chmod -R 755 $PWD/crosstool-ng/*
          PATH="${PATH}:$PWD/crosstool-ng/bin" make sdl2 CROSS_COMP=1 RELEASEBUILD=1
          mv ./fbneo ./FinalBurn\ Neo\ for\ CHA/
          mv ./metadata/hiscore.dat ./FinalBurn\ Neo\ for\ CHA/
          echo "${{ env.NOW }}" > ./FinalBurn\ Neo\ for\ CHA/fbneo_build_date.txt
          mv ./README.md ./FinalBurn\ Neo\ for\ CHA/_README_.TXT
          zip -9 -r ./FinalBurn\ Neo\ for\ CHA.zip ./FinalBurn\ Neo\ for\ CHA
          mkdir ./FinalBurn\ Neo\ for\ CHA\ -\ Help\ Videos
          mv *.mp4 ./FinalBurn\ Neo\ for\ CHA\ -\ Help\ Videos/
          zip -9 -r ./FinalBurn\ Neo\ for\ CHA\ -\ Help\ Videos.zip ./FinalBurn\ Neo\ for\ CHA\ -\ Help\ Videos
      - name: Compile fbneo_libretro.so
        run: |
          PATH="${PATH}:$PWD/crosstool-ng/bin" make -j$(nproc) -C src/burner/libretro generate-files platform=unix_rpi2 CROSS_CHA=1
          PATH="${PATH}:$PWD/crosstool-ng/bin" make -j$(nproc) -C src/burner/libretro platform=unix_rpi2 CROSS_CHA=1
          mv src/burner/libretro/fbneo_libretro.so ./fbneo_libretro.${{ env.NOW }}.so
          zip -9 fbneo_libretro.zip fbneo_libretro*.so
      - name: Release FinalBurn Neo for CHA
        uses: softprops/action-gh-release@master
        with:
          files: |
            ./FinalBurn\ Neo\ for\ CHA.zip
            ./FinalBurn\ Neo\ for\ CHA\ -\ Help\ Videos.zip
          tag_name: fbneo-${{ env.NOW }}
          generate_release_notes: true
          name: FinalBurn Neo for CHA (${{ env.NOW }})
      - name: Release FinalBurn Neo libretro core for CHA
        uses: softprops/action-gh-release@master
        with:
          files: ./fbneo_libretro.zip
          tag_name: libretro-fbneo-${{ env.NOW }}
          generate_release_notes: false
          name: FinalBurn Neo libretro core for CHA (${{ env.NOW }})
      - name: Release FinalBurn Neo libretro core for CHA
        uses: softprops/action-gh-release@master
        with:
          files: ./fbneo_libretro.zip
          tag_name: libretro-latest
          generate_release_notes: false
          name: FinalBurn Neo libretro core for CHA (${{ env.NOW }})
      - name: Release FinalBurn Neo for CHA
        uses: softprops/action-gh-release@master
        with:
          files: |
            ./FinalBurn\ Neo\ for\ CHA.zip
            ./FinalBurn\ Neo\ for\ CHA\ -\ Help\ Videos.zip
          tag_name: latest
          make_latest: true
          generate_release_notes: false
          name: FinalBurn Neo for CHA (${{ env.NOW }})
      - uses: sgpublic/delete-release-action@v1.2
        with:
          release-drop: true
          release-keep-count: 10
          release-drop-tag: false
          pre-release-drop: true
          pre-release-keep-count: -1
          pre-release-drop-tag: true
          draft-drop: true
          draft-drop-count: -1
