name: Compile FBNeo for CHA
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Sync fork"]
    types:
      - completed
env:
  GITHUB_TOKEN: ${{ github.token }}
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/chokogroup/ubuntu:18.10-glibc-2.28
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Compile FinalBurn Neo for CHA
        run: |
          NOW=$(date +%F)
          echo "NOW=$NOW" >> "$GITHUB_ENV"
          CROSS_COMP=1 RELEASEBUILD=1 make sdl2
          mv ./fbneo ./FinalBurn\ Neo\ for\ CHA/
          mv ./metadata/hiscore.dat ./FinalBurn\ Neo\ for\ CHA/
          echo "$NOW" > ./FinalBurn\ Neo\ for\ CHA/fbneo_build_date.txt
          mv ./README.md ./FinalBurn\ Neo\ for\ CHA/_README_.TXT
          zip -9 -r ./FinalBurn\ Neo\ for\ CHA/dats.zip ./dats
          zip -9 -r ./FinalBurn\ Neo\ for\ CHA.zip ./FinalBurn\ Neo\ for\ CHA
          mkdir ./FinalBurn\ Neo\ for\ CHA\ -\ Help\ Videos
          mv *.mp4 ./FinalBurn\ Neo\ for\ CHA\ -\ Help\ Videos/
          zip -9 -r ./FinalBurn\ Neo\ for\ CHA\ -\ Help\ Videos.zip ./FinalBurn\ Neo\ for\ CHA\ -\ Help\ Videos
      - name: Compile fbneo_libretro.so
        run: |
          CROSS_COMP=1 make -j$(nproc) -C src/burner/libretro generate-files platform=unix_rpi2
          CROSS_COMP=1 make -j$(nproc) -C src/burner/libretro platform=unix_rpi2
          mv src/burner/libretro/fbneo_libretro.so ./fbneo_libretro.${{ env.NOW }}.so
          zip -9 fbneo_libretro.zip fbneo_libretro*.so dats
      - name: Release FinalBurn Neo for CHA
        uses: softprops/action-gh-release@master
        with:
          files: |
            ./FinalBurn\ Neo\ for\ CHA.zip
            ./FinalBurn\ Neo\ for\ CHA\ -\ Help\ Videos.zip
            ./fbneo_libretro.zip
          tag_name: fbneo-${{ env.NOW }}
          make_latest: true
          name: FinalBurn Neo for CHA (${{ env.NOW }})
          body: Included FinalBurn Neo libretro core for CHA (${{ env.NOW }})
          generate_release_notes: true
      - name: Fix tags
        run: |
          git push --delete origin latest
          git push --delete origin libretro-latest
          git tag -d latest
          git tag -d libretro-latest
          git tag latest fbneo-${{ env.NOW }}
          git tag libretro-latest fbneo-${{ env.NOW }}
          git push origin --tags
      - name: Clean up old releases
        run: |
          gh api repos/${{ github.repository }}/releases --paginate --jq '.[15:] | .[] | "\(.id) \(.tag_name)"' | while read id tag; do
            gh api -X DELETE "repos/${{ github.repository }}/releases/$id" && gh api -X DELETE "repos/${{ github.repository }}/git/refs/tags/$tag" 2>/dev/null || true
          done
