name: Compile crosstools-ng

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Install needed tools
        run: |
          echo "NOW=$(date +%F)" >> "$GITHUB_ENV"
          sudo dpkg --add-architecture armhf
          sudo echo -e "Types: deb\nURIs: mirror+file:/etc/apt/apt-mirrors.txt\nArchitectures: amd64\nSuites: noble noble-updates noble-backports noble-security\nComponents: main universe restricted multiverse\nSigned-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg\n\nTypes: deb\nURIs: http://ports.ubuntu.com/\nArchitectures: armhf\nSuites: noble noble-updates noble-backports noble-security\nComponents: main universe restricted multiverse\nSigned-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg" | sudo tee /etc/apt/sources.list.d/ubuntu.sources
          sudo apt-get update
          sudo apt-get install --assume-yes curl ca-certificates build-essential autoconf flex texinfo help2man file gawk libtool-bin bison ncurses-dev binutils-multiarch zip git libudev-dev:armhf libsdl2-dev:armhf libsdl2-image-dev:armhf
          sudo apt-get autoremove; sudo apt-get autoclean
      - name: Compile crosstools-ng
        run: |
          git config --global --add safe.directory "$PWD"
          git clone https://github.com/crosstool-ng/crosstool-ng .
          git checkout
          rm -rf .git .gitignore .github
          curl -o m4/host-cpu-c-abi.m4 'https://gitlab.com/openconnect/openconnect/-/raw/master/m4/host-cpu-c-abi.m4?ref_type=heads&inline=false'
          export CT_PREFIX="$PWD/.build/install"
          ./bootstrap
          ./configure --enable-local
          make -j $(nproc)
          ./ct-ng armv7-rpi2-linux-gnueabihf
          curl -o crosstools-ng.patch 'https://raw.githubusercontent.com/ChokoGroup/FBNeo/refs/heads/master/crosstools-ng.patch'
          patch < crosstools-ng.patch
          env -u LD_LIBRARY_PATH ./ct-ng build CT_JOBS=$(nproc)
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: crosstool-ng-repo
          path: ./.build/install/
          overwrite: true
          compression-level: 9
          include-hidden-files: true
