name: Sync fork

# Controls when the workflow will run
on:
  schedule:
    - cron: '37 5 * * 5'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest
#    container: node:current-buster-slim
    steps:
      - name: Sync fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone "https://${GITHUB_REPOSITORY_OWNER}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
          git config --global --add safe.directory /__w/FBNeo/FBNeo
          git config user.name "${GITHUB_REPOSITORY_OWNER}"
          git config user.email "${GITHUB_REPOSITORY_OWNER}@users.noreply.github.com"
          git config --local user.password ${GITHUB_TOKEN}
          git remote add upstream "https://github.com/libretro/FBNeo.git"
          git checkout master
          git fetch upstream
          git merge upstream/master
          git push origin master
