name: Sync fork

on:
  schedule:
    - cron: '37 5 * * 5'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GITHUB_TOKEN: 
  UPSTREAM_URL: "https://github.com/libretro/FBNeo.git"
  WORKFLOW_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  UPSTREAM_BRANCH: "master"
  DOWNSTREAM_BRANCH: "master"
  FETCH_ARGS: ""
  MERGE_ARGS: ""
  PUSH_ARGS: ""
  SPAWN_LOGS: "false"


jobs:
  sync-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Upstream Repository
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with: 
          upstream_repo: ${{ env.UPSTREAM_URL }}
          upstream_branch: ${{ env.UPSTREAM_BRANCH }}
          downstream_branch: ${{ env.DOWNSTREAM_BRANCH }}
          token: ${{ env.WORKFLOW_TOKEN }}
          fetch_args: ${{ env.FETCH_ARGS }}
          merge_args: ${{ env.MERGE_ARGS }}
          push_args: ${{ env.PUSH_ARGS }}
          spawn_logs: ${{ env.SPAWN_LOGS }}